# Generated by Django 6.0.3 on 2026-04-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Araba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=100)),
                ('depo', models.IntegerField()),
                ('ortalamaHiz', models.IntegerField()),
                ('aldigiYolo', models.FloatField()),
            ],
        ),
    ]
