# Generated by Django 6.0.3 on 2026-04-02 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='araba',
            old_name='aldigiYolo',
            new_name='aldigiYol',
        ),
    ]
